"""empty message

Revision ID: 318f44d84e83
Revises: 40c7bedafc99
Create Date: 2018-02-21 13:10:32.873643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318f44d84e83'
down_revision = '40c7bedafc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
